### ISSUE TITLE
Example package tests

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/xbot2_examples#1]
@liesrock 

I have sort of completed this example package, I am now writing some documentation in markdown. When you have time, can you check that everything works and makes sense?

**Comment by liesrock** [comment]
I checked the examples and the related documentation and I do not see any major issue: I will run again the whole example package step by step to spot any possible errors/inconsistencies with the current version of the documentation.

**Comment by liesrock** [comment]
We can close this and have new issues in case
