### ISSUE TITLE
[XBot How To] Do I have to use a ControlPlugin to use the device/driver hyerarchy?

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/xbot2_examples#16]
I am following the code from _device_ folder, where Device, DeviceClient, Driver and their containers are defined. 
At the top, there is the rocket_plugin (which derives _ControlPlugin_) that does: 
`    _rocket = _robot->getDeviceInstance<Hal::RocketBase>("rocket_0");
`
To have the _rocket and its set, get methods.

I would like to have a similar things, but I do not want the node which uses the __rocket_ to be a ControlPlugin: because I do not want to define the on_init, starting, run ... methods.

So, what I have done is to define in a similar way all the driver, client and containers classes:
~~~c++
class XBotEEBase : virtual public XBot::Hal::DeviceBase
{

public:

    XBOT2_DECLARE_SMART_PTR(XBotEEBase)

    virtual bool setMotorPositionReference (std::string motor_name, double position_ref) = 0;
    
    virtual bool getMotorPosition (std::string motor_name, double &position) = 0; 

};   

using XBotEEClientBase = XBot::Hal::DeviceClientTpl<ROSEEPacket::Rx, ROSEEPacket::Tx>;
    

class XBotEEClient : public XBotEEClientBase,
                     public virtual XBotEEBase
{

public:

    using XBotEEClientBase::XBotEEClientBase;
    
    bool setMotorPositionReference (std::string motor_name, double position_ref) override;
    
    bool getMotorPosition (std::string motor_name, double &position) override; 

};

/**
 * @brief The RocketClientContainer class implements optional API
 * methods referring to multiple rockets together.
 */
class XBotEEClientContainer : public XBot::Hal::DeviceContainer<XBotEEClient>
{

public:

    using XBot::Hal::DeviceContainer<XBotEEClient>::DeviceContainer;

};



class XBotGazeboDriver : public XBot::Hal::DeviceDriverTpl<ROSEEPacket::Rx, ROSEEPacket::Tx>
{

public:

    XBotGazeboDriver(XBot::Hal::DeviceInfo devinfo);

    /**
     * @brief move_impl allows to override the tx data from
     * the framework before it's actually sent to the device
     */
    bool move_impl() override;

    /**
     * @brief sense_impl allows to override the rx data from
     * the device before it's actually sent to the framework
     * @return if return false, rx is not actually sent to
     * the framework!
     */
    bool sense_impl() override;

private:

    //std::chrono::nanoseconds _timeout;
};

/**
 * @brief The RocketDev class implements the client side
 * for all rocket device instances. If the protocol in use is
 * xbot2's client-server protocol, this is pure boilerplate
 * code that can be autogenerated. Otherwise, the user must
 * write the code to connect to the remote device.
 */
class XBotGazeboDriverContainer : public XBot::Hal::DeviceContainer<XBotGazeboDriver>
{

public:

    XBotGazeboDriverContainer(std::vector<XBot::Hal::DeviceInfo> devinfo);

    bool sense_all() override;

    bool move_all() override;

private:

    bool _srv_alive;

    XBot::ClientManager::UniquePtr _cli;

};
~~~

Now I want to access to XBotEEClient instance. I can not do a thing like `_rocket = _robot->getDeviceInstance<Hal::RocketBase>("rocket_0");` because I do not have the _robot, because the class is not a ControlPlugin.

So I randomly tried to create the "_rocket" instance (named     _xbot_ee_client here) : 
~~~c++
_xbot_ee_client = std::make_shared<ROSEE::XBotEEClient>(devinfo);
~~~

But there is some linking issue:
~~~
[ 95%] Built target UniversalFindActions
[ 97%] Built target rosee_gui_MainWindow
[ 98%] Linking CXX executable /home/tori/ROSEE/devel/lib/ros_end_effector/UniversalRosEndEffector
[100%] Built target rosee_gui_gui_main
/home/tori/ROSEE/devel/lib/libXBot2Hal.so: undefined reference to `ROSEE::XBotEEClient::XBotEEClient(XBot::Hal::DeviceInfo)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/tori/ROSEE/devel/lib/ros_end_effector/UniversalRosEndEffector] Error 1
~~~

So I do not know if:
- This is solvable, and I am missing some #include or some in the cmake
- This is unsolvable because I am using uncorrectly xbot2

**Comment by torydebra** [comment]
Instead, if I had to use the ControlPlugin, how can I costruct such type of object?
The costructor wants an Args argument. I think this is filled in some part of the xbotcore main node.

But I would like to "control" my ControlPlugin giving to it a command like the _thrust (I am always looking at the rocket example) using the methods. In the example _thrust is read by a file or the ROS service I think. So the only way to communicate with the ControlPlugin is through services? I can not have a ControlPlugin as a member of a wrapper class?

**Comment by alaurenzi** [comment]
Please explain your needs. I assume that the only user of the framework is the implementer of a control plugin. Within the HAL system, you directly manipulate the `_rx` and `_tx` structs, instead.

**Comment by torydebra** [comment]
Some updates on this.

Tecnically, what I want is to access to the Robot 

In these examples, _robot member is available because everything is a ControlPlugin

In xbot1 examples, there was another way:
~~~c++
std::string path_to_config_file = XBot::Utils::getXBotConfig();
auto robot = XBot::RobotInterface::getRobot(path_to_config_file);
~~~
This permit to access to `robot` from a node that is not a `ControlPlugin`

I tried to do this with xbot2. In the conf file, I had to add:
~~~
RobotInterface:
  framework_name: "ROS"
~~~
otherwise there was a point where some class complied that the "framework" has not been defined.

But now when calling 
`auto robot = XBot::RobotInterface::getRobot(path_to_config_file)`, I have this error: 
~~~console
[info] Generated joint id map as:
 joint_map:
  1: joint1
  2: joint2
  3: joint3
  4: joint4
  5: joint5
[ok  ] RobotInterface so library found! 
[ok  ] MODEL INTERFACE so library found! 
[info] Floating base model: FALSE
[info] Joint name: joint1 RBDL ID: 0
[info] Joint name: joint2 RBDL ID: 1
[info] Joint name: joint3 RBDL ID: 2
[info] Joint name: joint4 RBDL ID: 3
[info] Joint name: joint5 RBDL ID: 4
[ok  ] ModelInterfaceRBDL initialized successfully!
[info] Model ordered chains: 
arm

[info] Constructing ROS implementation of RobotInterface.. 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to connect to XBotCore
Annullato (core dump creato)
~~~

Then, is it possible to do this with xbot2?

**Comment by torydebra** [comment]
This error is not related to how I am using RobotInterface: also the other plugins (like homing) have the same problem

**Comment by torydebra** [comment]
Other updates. 
The error above seems solved. Now there are not crashes issues.

I am always trying to control the robot from a non _ControlPlugin_ . I did a main where I call: 
~~~c++
std::string path_to_config_file = XBot::Utils::getXBotConfig();
auto robot = XBot::RobotInterface::getRobot(path_to_config_file);
~~~
The robot pointer seems to be attached to the gazebo simulation, because if I move the robot in Gazebo (applying a casual force on some link through the GUI) I can see the joint positions changes with `robot->getJointPosition(q_pos)`

The problem is that I can not move the robot at all. I am trying:
- robot->setPositionReference(q) with all the control modes 
(applied with `robot->setControlMode(XBot::ControlMode::XXX());`

- robot->setVelocityReference(q) with velocity control mode

- Copying the homing examples: hence using the setting the joint positions to a robot model, and then call 
  `robot->setReferenceFrom(*model);`

- I tried to use XBot::RobotInterfaceXBot2Rt pointer instead XBot::RobotInterface pointer:
  - If I use `auto robot = std::dynamic_pointer_cast<XBot::RobotInterfaceXBot2Rt>(
        XBot::RobotInterface::getRobot(path_to_config_file));`, as you did in the xbot2_wip code (_xbot2_wip/src/rt_plugin/control_plugin.cpp_), the cast FAILS, the robot pointer is empty
  - If I use static cast version, pointer IS NOT empty, but I can still not move the robot as in the previous trials

(After all trials I do not forget to call robot->move())

I am still wondering if not using a ControlPlugin is not possible, or I am doing things wrong somewhere

**Comment by alaurenzi** [comment]
From an external ROS node, you can indeed use RobotInterface as you did. Only missing step is to enable the joint control via ros, which is done by the `ros_control` plugin. This is also mentioned [in the documentation](https://advrhumanoids.github.io/xbot2_wip/cheat.html#sending-joint-references) - it is very recent, incomplete, etc though

**Comment by torydebra** [comment]
Thanks! with `rosservice call /xbotcore/ros_ctrl/switch 1` I solved

**Comment by liesrock** [comment]
As we figured out discussing with @torydebra and @alaurenzi what @torydebra was looking for here was a _RobotInterfaceXBot2ROS_, which we will implement to control a robot outside the _ControlPlugin_ and using the ROS framework.
