### ISSUE TITLE
Rocket Device issues with ROS

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/xbot2_examples#19]
Hi I have some problem running the device example,

The device :
~~~yaml
rocket:
  names: [rocket_0]
  type: rocket
  thread: rt_main
~~~

causes this error : 
~~~console
[FATAL] [1604401333.006227926]: You must call ros::init() before creating the first NodeHandle
Couldn't find an AF_INET address for []
Couldn't find an AF_INET address for []
[ERROR] [1604401333.007628570]: [registerPublisher] Failed to contact master at [:0].  Retrying...
Couldn't find an AF_INET address for []
Couldn't find an AF_INET address for []
~~~

If I comment these lines in the config file the problem does not occur. 

---

If useful, when I change the thred type in _nrt_main_, other error happens:
~~~console
[info][nrt_main] 'nrt_main': initializing xbotcore thread with period = 0.005s, scheduler = 'SCHED_OTHER', priority = 0 
[err ][rocket] unable to reach XBot2 server: check that the robot is up and running 
terminate called after throwing an instance of 'XBot::ConnectionError'
  what():  Unable to open shared memory file '/xbot2_state_srv_to_cli_rocket': No such file or directory
Annullato (core dump creato)
~~~

**Comment by torydebra** [comment]
I am not sure what happened, but this issue is not a thing anymore. Probably I had some strange internal problems on my pc? Today it works

**Comment by liesrock** [comment]
So this are things usually related with ROS network configuration, maybe something has changed.

**Comment by torydebra** [comment]
Same error of IF_NET address occurred again recently. This time I solved reinstalling xbot from the nightly build linked here https://github.com/ADVRHumanoids/ROSEE-GraspPlanner/issues/5
