### ISSUE TITLE
How could I run an example and simulate the robot on Rviz?

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/xbot2_examples#27]
## Point

I would like to run an example and simulate the robot on Rviz, how could I do it? For example, I have my simple example: homing and I am able to run it on gazebo, how could I do if I would desire to run it on Rviz? Thank you in advance!

@liesrock @alaurenzi

**Comment by alaurenzi** [comment]
HI @lia2790,
you can run a "dummy" mode with `--hw dummy`

**Comment by liesrock** [comment]
Ciao @lia2790 : the issue is related with the config file.

I helped @torydebra to fix this in https://github.com/ADVRHumanoids/TelePhysicalOperation/tree/centauro/telephysicaloperation/config

Please try to speak with him (@torydebra) to have more insight and we will later update this issue.

**Comment by lia2790** [comment]
Hi @liesrock, @torydebra, thank you for your answer and help me.. I will speak with davide...

**Comment by liesrock** [comment]
more insight of the work done can be found here: https://github.com/ADVRHumanoids/xbot2_wip/issues/43

**Comment by lia2790** [comment]
I have not access

**Comment by lia2790** [comment]
Thanks to all, I am finally able to run xbot2 core successfully with the right config files (can you see them [here](https://github.com/lia2790/CartesioTests/tree/main/CartesioTestsCpp/configs/xbot)). thanks!
