### ISSUE TITLE
relative path of srdf urdf and joint map

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/xbot2_examples#3]
With my installation configuration (that is not the superbuild), the relative path in the config yaml file do not work:
~~~console
tori@turing:~$ xbot2-core --verbose
ERROR in computeAbsolutePath : the input path  config/teleop_fixed_base.urdf is neither an absolute path nor related with the robotology superbuild. Download it!
ERROR in computeAbsolutePath : the input path  config/teleop_fixed_base.srdf is neither an absolute path nor related with the robotology superbuild. Download it!
~~~

I solved putting the absolute path instead of  _config/teleop_fixed_base.urdf_

**Comment by alaurenzi** [comment]
Cleaner solution is to set the `XBOT_ROOT` env variable appropriately

**Comment by torydebra** [comment]
Yes, I have not that variable set. But where it should point? To xbot2 install folder? Or to the debians in /opt/xbot/... ?

**Comment by torydebra** [comment]
> Yes, I have not that variable set. But where it should point? To xbot2 install folder? Or to the debians in /opt/xbot/... ?

To the root of xbot2_examples :D, solved
