### ISSUE TITLE
[XBOT2] External wrench computation

### ISSUE THREAD

**Issue by MarcoMagriDev** [ADVRHumanoids/xbot2_examples#34]
Hi,

I was wondering, is there any builtin method in `xbot2` to get the current wrench applied to the robot TCP?

Thanks,
Marco

**Comment by alaurenzi** [comment]
There is nothing provided built-in (unless the robot mounts a physical FT sensor)
For estimation purposes you can have a look to [this package](https://github.com/ADVRHumanoids/estimation_utils)

**Comment by MarcoMagriDev** [comment]
I will try to have a look of that.

Thanks
